language: cpp

compiler:
  - gcc

before_install:
  # for gcc with C++11 support
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  # update to gcc with C++11 support
  - sudo apt-get -qq install gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  # install latest LCOV (1.9 was failing)
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  # init coverage to 0 (optional)
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make && ctest --verbose

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'externals/*' 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  #- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
  - coveralls-lcov coverage.info
